#!/usr/bin/env python

from gi.repository import Gtk
from gi.repository import AppIndicator3 as ai

import yaml, sys, os
import os.path as p

CONFIG_FILE = '/etc/sleepr'

class PreferencesWindow:
    def __init__(self):
        builder = Gtk.Builder.new()

        ui = p.realpath(p.join(p.dirname(sys.argv[0]), '..', 'lib', 'preferences-window.glade'))
        
        try:
            builder.add_from_file(ui)
        except:
            print "Can't load UI"
            raise

        self.__w = builder.get_object("PreferencesWindow")

        self.config = self.load_config()

        self.beginHours = builder.get_object("spnBeginHours")
        self.beginHours.set_range(0, 23)
        self.beginHours.set_increments(1, -1)
        self.beginHours.set_wrap(True)
        self.beginHours.set_value(self.config['at'][0])

        self.beginMinutes = builder.get_object("spnBeginMinutes")
        self.beginMinutes.set_range(0, 59)
        self.beginMinutes.set_increments(1, -1)
        self.beginHours.set_wrap(True)
        self.beginMinutes.set_value(self.config['at'][1])

        self.endHours = builder.get_object("spnEndHours")
        self.endHours.set_range(0, 23)
        self.endHours.set_increments(1, -1)
        self.beginHours.set_wrap(True)
        self.endHours.set_value(self.config['until'][0])

        self.endMinutes = builder.get_object("spnEndMinutes")
        self.endMinutes.set_range(0, 59)
        self.endMinutes.set_increments(1, -1)
        self.beginHours.set_wrap(True)
        self.endMinutes.set_value(self.config['until'][1])

        self.cancelButton = builder.get_object("btnCancel")
        self.cancelButton.connect("clicked", self.__cancel)

        self.okButton = builder.get_object("btnOK")
        self.okButton.connect("clicked", self.__ok)


    def show(self):
        self.__w.show()

    def load_config(self):
        try:
            f = open(CONFIG_FILE, 'r')
            return yaml.load(f.read())
        except:
            print "Can't read file '%s'" % CONFIG_FILE 

    def save_config(self, config):
        for k in ['at', 'until']:
            if config[k]:
                self.config[k] = config[k]

        try:
            f = open(CONFIG_FILE, 'w')
            f.write(yaml.dump(self.config))
        except:
            print "Can't write to file '%s'" % CONFIG_FILE

    def quit(self):
        Gtk.main_quit()
        sys.exit(0)

    # callbacks

    def __cancel(self, w):
        self.quit()

    def __ok(self, w):
        self.save_config({
            'at' : [
                int(self.beginHours.get_value()),
                int(self.beginMinutes.get_value()) ],
            'until' : [
                int(self.endHours.get_value()),
                int(self.endHours.get_value()) ] })

        self.quit()

if __name__ == "__main__":
    PreferencesWindow().show() 
    Gtk.main()
